version: '3.2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.4.2
    environment:
      - discovery.type=single-node
    networks:
      - elk
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.4.2
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge
